# Generated by Django 4.0.5 on 2022-06-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_countries_departments_dependents_employees_jobs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'managed': False, 'verbose_name_plural': 'countries'},
        ),
    ]
